### ISSUE TITLE
Sarif support for integration with GitHub security

### ISSUE THREAD

**Issue by ds-dustenharrison** [MarketSquare/robotframework-robocop#638]
Can you add Sarif export support to the export of the scans so the data can be uploaded to GitHub Advanced Security? This would give us a consolidated view of all the code quality issues.

**Comment by bhirsz** [comment]
Usually I would prefer to not implement it in Robocop (since we would now need to support it). But after quick look at sarif I see it would be easier to implement it in our core code. So we can do this - hovewer could you help with testing the output? I don't have anything that uses sarif output, I can cover the export with unit test but it would be nice to have someone to actually test it live.

I think it could be implemented as a report class, creating the file after the run.

**Comment by bhirsz** [comment]
Leaving some resources for me:

Sarif docs: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning

Validate sarif file: https://sarifweb.azurewebsites.net/

**Comment by ds-dustenharrison** [comment]
I would be glad to help when you are ready. Unfortunately due to the fact, that our code is proprietary I can't run this against a public repo.
I can however create the GitHub action and have it upload the results to our test repo and then share the output with you. 
I would just need some assistance on the parameters to run against the existing code and the parameters for running using the sarif output. Then I can provide the output of both.

**Comment by bhirsz** [comment]
Sure, I will let you know - when I learn more about the format I could figure out the best way of using it (testing) as well. I could also try to setup github action on our repo as well. I can see that there are lot of optional fields so we can do it iteratively, starting from required ones.

**Comment by ds-dustenharrison** [comment]
Sounds great. Thank you

**Comment by bhirsz** [comment]
I've created early POC (not yet mergable) in #653 together with example Github action that runs the Robocop and uploads Sarif file. You can see it's able to detect the issues from the file:

![image](https://user-images.githubusercontent.com/8532066/180640373-e9675ff5-d2fa-4e5a-945b-ef58cce40175.png)

More details on single issue:
![image](https://user-images.githubusercontent.com/8532066/180640409-883e27ae-12a5-4b1d-8ef1-b7a68912a038.png)

It appears to work, I will now focus on tweaking and improving the code and adding the tests.

**Comment by bhirsz** [comment]
BTW thanks for this issue - now I've learned about this format and it looks like good way to solve some of our issues (like #414 which is on hold due to issues with native github API) or creating html reports (thanks to tools handling sarif output).

**Comment by bhirsz** [comment]
Merged the PR with sarif report. It will be included in the next release (2.4.0) in the next few days. 

I have also created new page in our docs - CI - that will include information how to integrate Robocop with various CI/CD platforms (hopefully it will grow over the time). There is open PR with first addition - how to configure Github workflow to use SARIF to register issues in Github Code Scanning - #657 .

**Comment by ds-dustenharrison** [comment]
Looks like it is not quite working. Here is what I have in my github action:
python -m robocop --reports sarif.json .
However, when I look at the directory the sarif file is not there
Run pwd
pwd
ls -lha
shell: /usr/bin/bash -e {0}
shell: /usr/bin/bash -e {0}
/home/runner/work/qa-testing-robocop/qa-testing-robocop
total 64K
drwxr-xr-x 10 runner docker 4.0K Aug [2](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:2)4 18:22 .
drwxr-xr-x [3](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:3) runner docker [4](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:4).0K Aug 24 18:22 ..
drwxr-xr-x 8 runner docker 4.0K Aug 24 18:22 .git
drwxr-xr-x 3 runner docker 4.0K Aug 24 18:22 .github
drwxr-xr-x 3 runner docker 4.0K Aug 24 18:22 .idea
drwxr-xr-x 4 runner docker 4.0K Aug 24 18:22 Data
-rw-r--r-- 1 runner docker 17[5](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:5) Aug 24 18:22 Dockerfile
drwxr-xr-x 4 runner docker 4.0K Aug 24 18:22 Library
-rw-r--r-- 1 runner docker 80 Aug 24 18:22 README.md
drwxr-xr-x 5 runner docker 4.0K Aug 24 18:22 Resources
drwxr-xr-x 7 runner docker 4.0K Aug 24 18:22 Tests
drwxr-xr-x 2 runner docker 4.0K Aug 24 18:22 Tools
-rw-r--r-- 1 runner docker 1.5K Aug 24 18:22 execution_order.dat
-rw-r--r-- 1 runner docker 519 Aug 24 18:22 main.py
-rw-r--r-- 1 runner docker 29[6](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:7) Aug 24 1[8](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:9):22 requirements.txt
-rwxr-xr-x 1 runner docker [9](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:10)44 Aug 24 [18](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:19):[22](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001583328?check_suite_focus=true#step:5:23) rfdocker

**Comment by bhirsz** [comment]
You need to pass ``sarif`` to reports:
```
python -m robocop --reports sarif .
```

The report will be generated in ``.sarif.json`` file. You can configure the output directory or filename by configuring the report:
```
robocop --reports sarif --configure sarif:output_dir=C:/sarif_reports --configure sarif:report_filename=.sarif
```

But I think it's possible bug - it should fail on unrecognized report name (such as ``sarif.json`` instead of ``sarif``).

**Comment by ds-dustenharrison** [comment]
I changed it and the file is still not there
     run: |
        python -m robocop --reports sarif .
    - name: List dir
      run: |
        pwd
        ls -lha
        shell: /usr/bin/bash -e {0}

/home/runner/work/qa-testing-robocop/qa-testing-robocop
total 64K
drwxr-xr-x 10 runner docker 4.0K Aug 24 18:43 .
drwxr-xr-x  3 runner docker 4.0K Aug 24 18:43 ..
drwxr-xr-x  8 runner docker 4.0K Aug 24 18:43 .git
drwxr-xr-x  3 runner docker 4.0K Aug 24 18:43 .github
drwxr-xr-x  3 runner docker 4.0K Aug 24 18:43 .idea
drwxr-xr-x  4 runner docker 4.0K Aug 24 18:43 Data
-rw-r--r--  1 runner docker  1[7](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001940962?check_suite_focus=true#step:5:8)5 Aug 24 1[8](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001940962?check_suite_focus=true#step:5:9):43 Dockerfile
drwxr-xr-x  4 runner docker 4.0K Aug 24 18:43 Library
-rw-r--r--  1 runner docker   80 Aug 24 18:43 README.md
drwxr-xr-x  5 runner docker 4.0K Aug 24 18:43 Resources
drwxr-xr-x  7 runner docker 4.0K Aug 24 18:43 Tests
drwxr-xr-x  2 runner docker 4.0K Aug 24 18:43 Tools
-rw-r--r--  1 runner docker 1.5K Aug 24 18:43 execution_order.dat
-rw-r--r--  1 runner docker  51[9](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001940962?check_suite_focus=true#step:5:10) Aug 24 [18](https://github.com/LiveoakTechnologies/qa-testing-robocop/runs/8001940962?check_suite_focus=true#step:5:19):43 main.py
-rw-r--r--  1 runner docker  296 Aug 24 18:43 requirements.txt
-rwxr-xr-x  1 runner docker  944 Aug 24 18:43 rfdocker

**Comment by bhirsz** [comment]
Duh..it looks like I forgot to make release! Now it makes sense why it didnt fail on unknown report -since failing on unknown names was added aro7bd the same timer as sarif report. I aoologise for that, I will release the changes tommorow and let you known in this issue.

**Comment by ds-dustenharrison** [comment]
Did you know when the commit will be part of the release? I just tried again this morning and I am still not seeing the file on the GH runner file system.

**Comment by bhirsz** [comment]
I had some issues but it is now resolved and ``sarif`` report is now part of ``2.4.0`` release. Thank you for your patience!

**Comment by ds-dustenharrison** [comment]
It did work now. Thank you. I am still seeing an exit code 255 after the scan but the sarif did get uploaded to GitHub Security.
